name: Publish to npm

on:
  # 触发条件1：main 分支收到 push 后执行任务。
  push:
    branches:
      - main
  # 触发条件2：手动按钮
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: 更新版本号
        run: |
          git config --global user.email "3332664073@qq.com"
          git config --global user.name "aizhiqian"
          npm version patch --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          git add package.json
          git commit -m "Update version to $VERSION"
          git push

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
